### ISSUE TITLE
How to generate EXPS for Real World Data?

### ISSUE THREAD

**Issue by GaganBhat** [mims-harvard/GraphXAI#66]
Thanks for this great work! 

I was looking to run real world examples with MUTAG, and noticed that the `formal/realworld/mutag/EXPS` directory was missing.

This directory is utilized by [graph_eval.py](https://github.com/mims-harvard/GraphXAI/blob/eba0e390e231aaae1cb2709cb450ae393af4e61d/formal/realworld/graph_eval.py#L65) and it searches for *.pt files inside.

How can I get this data?

**Comment by chirag126** [comment]
Thank you for your interest in our work, Gagan! All the datasets used in our work can be downloaded from https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/KULOS8

**Comment by GaganBhat** [comment]
While not a dataset related, this was a silly issue -- I just had to manually create the intermediary directories for the explanations `EXPS/SUBX`, `EXPS/GRAD`, etc... and it just worked fine.

Thanks for the quick response!
