### ISSUE TITLE
No module named 'graphxai.utils'

### ISSUE THREAD

**Issue by ZhongLIFR** [mims-harvard/GraphXAI#69]
Thanks for the great work. I have installed graphxai using github. It shows errors when I try to import graphxai in python. Please check details below:
```
  File "<ipython-input-328-53dd77503f89>", line 1, in <module>
    import graphxai

  File "/opt/anaconda3/lib/python3.8/site-packages/graphxai/__init__.py", line 1, in <module>
    from graphxai.utils.explanation import Explanation

ModuleNotFoundError: No module named 'graphxai.utils'
```

**Comment by chirag-agarwall** [comment]
Thank you for your interest in our work. Please find below the exact steps you can try to install the package cleanly.

1. git clone https://github.com/mims-harvard/GraphXAI.git
2. cd GraphXAI
3. pip install -e .

Output:
   Preparing metadata (setup.py) ... done
   Installing collected packages: graphxai
   Running setup.py develop for graphxai
   Successfully installed graphxai-0.1

Check:
python
Python 3.11.3 (main, Apr  7 2023, 21:05:46) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
> import graphxai
> from graphxai.utils.explanation import Explanation

Runs successfully!

Please let me know if this help.s

**Comment by ZhongLIFR** [comment]
Thank you for you prompt reply.  It works now by following your instructions. However, I find that I still need to add the following code before importing graphxai (BTW, I am working on MacOS M1):
```
import sys
sys.path.append('//Users/zlifr/GraphXAI')
import graphxai
```

**Comment by jonasjuerss** [comment]
I'm experiencing the same problem under Windows. Appending to `sys.path` does not resolve the issue in my case.
